### PR TITLE
Bump nvm-version to current LTS

### PR DESCRIPTION
**Pull request by villeristi**
As described in title.

### CODE REVIEW

**Review by cniska — CHANGES_REQUESTED** [review]
I think we should use **8.9** instead of the precise one.

**Review by cniska — APPROVED** [review]

**Comment by Jalle19** [comment]
Target branch is probably wrong?

**Comment by cniska** [comment]
Yes, this change should be merged into **master**.

**Comment by villeristi** [comment]
Closing due to wrong target & too much huzzle on fixing the conflicts. Will open a new one instead.

**Pull request closed without merging**
