### PR TITLE
Added image-webpack-loader and config.js modified accordingly

### PR DESCRIPTION
**Pull request by Kotpes**

### CODE REVIEW

**Comment by Kotpes** [comment]
Now should be good @hugovk 
The point of this commit is to use `image-webpack-loader` to handle all sorts of images out of the box

**Comment by cniska** [comment]
**Don't merge this yet, the configuration has not beed tested!**

@Kotpes could you check if this change is even necessary now that that this project is based on CRA?

**Comment by Kotpes** [comment]
@crisu83 This nag (`image-webpack-loader`) optimizes images as well. If we don't need it - no point of merging.

**Comment by cniska** [comment]
@Kotpes I'm not sure, do you think we need it in this boilerplate?

**Comment by Kotpes** [comment]
@crisu83 It's not necessity, so no, we don't need it

**Pull request closed without merging**
