### PR TITLE
Rebase on latest CRA

### PR DESCRIPTION
**Pull request by cniska**
Upgrading from Webpack 1 to Webpack 3 is no small task, so I decided to "rebase" this project on the latest version of CRA.

To do this, I took the following steps:

- [x] Create a new empty CRA app and ejected it
- [x] Replace the contents of `config` and `scripts` -folders with the ones from CRA
- [x] Replace `package.json` with the one from CRA
- [x] Re-add all the missing packages and scripts that are part of this boilerplate
- [x] Move dependencies that are only necessary for development to `devDependencies`
- [x] Fix all Flow issues
- [x] Ensure that everything works

### CODE REVIEW

**Comment by cniska** [comment]
Yay!

**Comment by Kotpes** [comment]
@crisu83 Is `flow-typed/npm/` supposed to be in repo?

**Comment by cniska** [comment]
@Kotpes Yes they should, they are typing for non-typed libraries from the community.

**Review by Kotpes — APPROVED** [review]
Looks good

**Comment by cniska** [comment]
@Kotpes Thanks

**Pull request merged**
